name: "finview_lite"
description: "FinView Lite is a sleek Flutter dashboard designed to give users a clear, concise overview of their investments, complete with dynamic charts and customizable return views."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: 0.68.0
  shared_preferences: ^2.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/portfolio.json
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/icons/icon.png"
  image_dark: assets/icons/icon.png
  android: true
  ios: true
  web: false


